#!/usr/bin/env python3
"""
Export weights from the unzipped PyTorch checkpoint (data.pkl + data/<N> raw
storages) into CUDA-deployable artifacts:

  - weights.bin : all tensors concatenated, little-endian float32
  - weights.h   : C header with embedded arrays + offset manifest

No PyTorch required: in the zip-checkpoint format each data/<N> file is the
raw storage bytes of one tensor (little-endian, dtype = FloatStorage here).
Tensor -> storage mapping was recovered from data.pkl with a stub unpickler.
"""
import struct, os, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
OUT  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src")

# (name, storage_file, shape) — exact order used by the CUDA runtime.
TENSORS = [
    ("head_bias",           "0",  (1, 12, 1, 1)),
    ("head_block1_0_weight","1",  (12, 4, 5, 5)),
    ("head_block1_0_bias",  "2",  (12,)),
    ("head_block1_1_prelu", "3",  (12,)),          # PReLU slope (learnable)
    ("head_block1_2_weight","4",  (12, 12, 3, 3)),
    ("head_block1_2_bias",  "5",  (12,)),
    ("head_block2_weight",  "6",  (12, 4, 5, 5)),
    ("head_block2_bias",    "7",  (12,)),
    ("body_bias",           "8",  (1, 12, 1, 1)),
    ("body_block1_weight",  "9",  (12, 12, 3, 3)),
    ("body_block1_bias",    "10", (12,)),
    ("body_block2_weight",  "11", (12, 12, 1, 1)),
    ("body_block2_bias",    "12", (12,)),
    ("att_1_weight",        "13", (12, 12, 1, 1)),
    ("att_1_bias",          "14", (12,)),
    ("att_2_prelu",         "15", (12,)),          # PReLU slope (learnable)
    ("att_3_weight",        "16", (12, 12, 1, 1)),
    ("att_3_bias",          "17", (12,)),
    ("tail_1_weight",       "18", (3, 3, 3, 3)),
    ("tail_1_bias",         "19", (3,)),
]

def numel(shape):
    n = 1
    for d in shape:
        n *= d
    return n

def main():
    os.makedirs(OUT, exist_ok=True)
    blobs, offsets, off = [], {}, 0
    for name, sfile, shape in TENSORS:
        path = os.path.join(ROOT, "data", sfile)
        raw = open(path, "rb").read()
        n = numel(shape)
        assert len(raw) == 4 * n, f"{name}: {len(raw)} bytes != {4*n} expected"
        blobs.append(raw)
        offsets[name] = (off, n, shape)
        off += n

    blob = b"".join(blobs)
    with open(os.path.join(OUT, "weights.bin"), "wb") as f:
        f.write(blob)

    vals = struct.unpack(f"<{off}f", blob)
    with open(os.path.join(OUT, "weights.h"), "w") as f:
        f.write("// Auto-generated by export_weights.py — do not edit.\n")
        f.write("#pragma once\n\n")
        f.write(f"#define TOTAL_WEIGHT_FLOATS {off}\n\n")
        for name, (o, n, shape) in offsets.items():
            f.write(f"#define {name.upper()}_OFFSET {o}\n")
            f.write(f"#define {name.upper()}_SIZE   {n}   // shape {shape}\n")
        f.write("\n// All weights, concatenated in manifest order (float32).\n")
        f.write("static const float MODEL_WEIGHTS[TOTAL_WEIGHT_FLOATS] = {\n")
        for i in range(0, off, 8):
            row = ", ".join(f"{v:.9e}f" for v in vals[i:i+8])
            f.write(f"  {row},\n")
        f.write("};\n")

    print(f"Wrote weights.bin ({len(blob)} bytes) and weights.h ({off} floats)")
    # quick sanity stats
    import statistics
    print(f"min={min(vals):.6f} max={max(vals):.6f} mean={statistics.fmean(vals):.6f}")

if __name__ == "__main__":
    main()
